# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

parameters:
- name: tmpDirVar
  type: string
  default: tmpDir
- name: hostArch
  type: string
  default: amd64
- name: targetPlatform
  type: string
- name: vsDevCmdArch
  type: string
- name: buildOutputLocationVar
  type: string
  default: buildOutputLocation
- name: numShards
  type: number
  default: 8
jobs:
- job: '$build_{{ parameters.targetPlatform }}'
  variables:
    fixedFlags: '--timeout=240;--shuffle;-DTEST_BUILD_ONLY=TRUE'
    parallelismFlag: '-j$(testParallelism)'
    xmlOutputFlag: '--xunit-xml-output=$(${{ parameters.buildOutputLocationVar }})/test-results.xml'
    shardFlags: '--num-shards=$(System.TotalJobsInPhase);--run-shard=$(System.JobPositionInPhase)'
    litFlags: '$(fixedFlags);$(parallelismFlag);$(xmlOutputFlag);$(shardFlags)'
  strategy:
    parallel: ${{ parameters.numShards }}
  timeoutInMinutes: 360
  steps:
  - script: |
      if exist "$(${{ parameters.tmpDirVar }})" (rmdir /S /Q $(${{ parameters.tmpDirVar }}))
      mkdir $(${{ parameters.tmpDirVar }})
    displayName: 'Setup TMP Directory'

  - checkout: self
    clean: true
    submodules: false

  - template: checkout-sources.yml
  - template: vcpkg-dependencies.yml
    parameters:
      targetPlatform: ${{ parameters.targetPlatform }}
  - template: cmake-configure-build.yml
    parameters:
      targetPlatform: ${{ parameters.targetPlatform }}
      hostArch: amd64
      targetArch: ${{ parameters.vsDevCmdArch }}
  - template: run-tests.yml
    parameters:
      hostArch: ${{ parameters.hostArch }}
      targetPlatform: ${{ parameters.targetPlatform }}
      targetArch: ${{ parameters.vsDevCmdArch }}
      displayName: 'Build Tests'
